extends:
  - eslint:recommended
  - standard
  - prettier
  - prettier/standard
plugins:
  - standard
  - prettier
env:
  es6: true
  node: true
rules:
  camelcase: 0
  no-var: 2
  prefer-const: 2
  no-console: 0
  no-else-return: "error"
  no-useless-concat: "error"
  prefer-template: "error"
  no-process-env: "error"
